CREATE TABLE user_dados(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_nome VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
)